version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env-web

  db:
    image: mysql:9.0
    env_file: .env-db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: