version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env-web

  db:
    image: mysql:9.0
    env_file: .env-db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: